/**
 * @file Application event names. String constants — no magic strings in code.
 */

export const AppEvents = Object.freeze({
  // File lifecycle
  FILE_A_SELECTED: 'FILE_A_SELECTED',
  FILE_B_SELECTED: 'FILE_B_SELECTED',
  FILE_A_REMOVED: 'FILE_A_REMOVED',
  FILE_B_REMOVED: 'FILE_B_REMOVED',

  // Mapping
  MAPPING_UPDATED: 'MAPPING_UPDATED',
  NORMALIZATION_UPDATED: 'NORMALIZATION_UPDATED',

  // Comparison
  COMPARE_REQUESTED: 'COMPARE_REQUESTED',
  COMPARE_PROGRESS: 'COMPARE_PROGRESS',
  COMPARE_SUCCEEDED: 'COMPARE_SUCCEEDED',
  COMPARE_FAILED: 'COMPARE_FAILED',

  // Results
  RESULT_FILTER_CHANGED: 'RESULT_FILTER_CHANGED',
  RESULT_RECORD_OPENED: 'RESULT_RECORD_OPENED',
  RESULT_RECORD_CLOSED: 'RESULT_RECORD_CLOSED',

  // Export / reset
  EXPORT_REQUESTED: 'EXPORT_REQUESTED',
  RESET_REQUESTED: 'RESET_REQUESTED',

  // UI
  TOAST_SHOWN: 'TOAST_SHOWN',
  TOAST_DISMISSED: 'TOAST_DISMISSED',
});